config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"users#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :messages, only: [:index, :create]
  resources :rooms, only: [:create, :show, :index]
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def index
    @messages = Message.all.order(created_at: :desc)
    @currentEntries = current_user.entries
    myRoomIds = []
  
    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end
  
    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',current_user)
  end

  def create
    if Entry.where(user_id: current_user.id, room_id: params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(user_id: current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= form_with(model: message, local: true) do |form|
  - if message.errors.any?
    #error_explanation
      %h2
        = pluralize(message.errors.count, "error")
        prohibited this message from being saved:
      %ul
        - message.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :content
    = form.text_field :content
  .actions
    = form.submit

app/views/messages/edit.html.haml
%h1 Editing Message
= render 'form', message: @message
= link_to 'Show', @message
= link_to 'Back', messages_path

app/views/messages/index.html.haml
= render "posts/header"

.room-top
  トーク一覧
- @anotherEntries.each do |e|
  = link_to room_path(e.room.id) do
    .room-list
      .room-list__image
        -if e.user.image?
          = image_tag "#{e.user.image.url}", class: "message-user-image"
        -else
          = image_tag "siruetto.jpg", class: "message-user-image"
      .room-list__talk-box
        .room-list__talk-box__name
          = e.user.name
        .room-list__talk-box__last-talk
          - if e.room.messages.order(created_at: :desc).take.try(:content).present? 
            = e.room.messages.order(created_at: :desc).take.try(:content).truncate(20)
          -else
            まだメッセージはありません。
= render "posts/footer"

app/views/messages/new.html.haml
%h1 New Message
= render 'form', message: @message
= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice
%p
  %strong Content:
  = @message.content
= link_to 'Edit', edit_message_path(@message)
|
= link_to 'Back', messages_path