config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"users#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :messages, only: [:index, :create]
  resources :rooms, only: [:create, :show, :index]
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, presence: true, length: { maximum: 6 }
  mount_uploader :image, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end

  def show
    @name = current_user.name
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path, notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image, :activity, :sex, :age, :birthday, :position, :introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
= render "posts/header"

.account-page
  .account-page__top
    プロフィール変更
  .account-page__content
    = form_with(model: @user, local: true) do |form|
      .account-page__content__photo
        = form.label :image, class: 'image' do
          - if @user.image.present?
            = image_tag "#{(@user.image).to_s}", alt: "preview", id: :img_prev_edit, class: "image-btn"
            = form.file_field :image
          - else
            = image_tag "siruetto.jpg", alt: "preview", id: :img_prev_edit, class: "image-btn"
            = form.file_field :image
      .account-page__content__profile-name
        名前
      = form.text_field :name, placeholder: "名前を入力して下さい" , rows: "20", class: 'title-box'
      .account-page__content__profile-activity
        活動エリア
      = form.select :activity, [ ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"], ["茨城県"], ["栃木県"] ,["群馬県"], ["埼玉県"], ["千葉県"], ["東京都"], ["神奈川県"] ,["新潟県"], ["富山県"], ["石川県"], ["福島県"], ["山梨県"] ,["長野県"], ["岐阜県"], ["静岡県"], ["愛知県"], ["三重県"] ,["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"], ["奈良県"] ,["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"] ,["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"] ,["佐賀県"], ["長崎県"], ["熊本県"], ["大分県"], ["宮崎県"] ,["鹿児島県"], ["沖縄県"] ], prompt: "選択してください"
      .account-page__content__profile-sex
        性別
      = form.radio_button :sex, "男" 
      男
      = form.radio_button :sex, "女"
      女
      .account-page__content__profile-age
        年齢
      = form.number_field :age, class: 'age-box'
      歳
      .account-page__content__profile-birthday
        生年月日
      = form.date_select :birthday, {start_year: 1800, end_year: 2020}, {start_year: 1990}
      .account-page__content__profile-position
        得意ポジション
      = form.select :position, [ ["ピッチャー"], ["キャッチャー"], ["ファースト"], ["セカンド"], ["サード"], ["ショート"], ["レフト"], ["センター"], ["ライト"] ], prompt: "選択してください"
      .account-page__content__profile-introduction
        自己紹介
      = form.text_area :introduction, class: 'introduction-box'
      .account-page__content__profile-submit
        = form.submit :変更する, class: 'btn-submit'
        
.footer

app/views/users/index.html.haml
.top-page
  .top-page__box
    .top-page__box__title.wow.fadeInUp
      一緒に野球しようよ
    .top-pag__box__login.wow.fadeInUp
      - if user_signed_in?
        = link_to "トップページ", posts_path, class: "toppage-btn"
        
        = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        = link_to "ユーザーを登録する", new_user_registration_path
        %br/
        = link_to "ログインする", new_user_session_path

app/views/users/show.html.haml
= render "posts/header"

.name-box
  .name-box__picture
    -if @user.image?
      = image_tag @user.image.url
    -else
      = image_tag "siruetto.jpg"
.user-content
  .user-content__profile
    .user-content__profile__title
      = @user.name
      さんのプロフィール
    .user-content__profile__icon
      - if @user.id == current_user.id
        = link_to  edit_user_path, class: "btn-edit" do
          = icon('fas', 'cog')
      - else
        - if @isRoom == true
          %p
            %a{href: "/rooms/#{@roomId}"} チャットへ
        - else
          = form_for @room do |f|
            = fields_for @entry do |e|
              = e.hidden_field :user_id, value: @user.id
            = f.submit "チャットを始める"
          
  .user-content__activity
    　　活動エリア　　　
    = @user.activity
  .user-content__sex
    　　性別　　　　　　
    = @user.sex
  .user-content__age
    　　年齢　　　　　　
    = @user.age
    歳
  .user-content__birthday
    　　生年月日　　　　
    = @user.birthday
    
  .user-content__position
    　　得意ポジション　
    = @user.position
  .user-content__introduction
    .user-content__introduction__text-name
      自己紹介
    .user-content__introduction__text-box
      = @user.introduction

= render "posts/footer"