config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"users#index"
  resources :users, only: [:index, :show, :edit, :update]
  resources :messages, only: [:index, :create]
  resources :rooms, only: [:create, :show, :index]
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :date, :area_id, :postal, :place, :venue, :capacity, :remarks, presence: true

  def self.search(search)
    return Post.all unless search
    Post.where('area_id  LIKE(?)', "%#{search}%")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show]
  # before_action :setting_post, only: [:update, :destroy]

  def index
    @posts = Post.all.order(id: "DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: '投稿が送信されました'
    else
      redirect_to new_post_path, notice: '入力してください。'
    end
  end

  def show
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @post.user.id)
    if @post.user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path, notice: '更新しました'
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path, notice: '削除しました'
  end

  def search
    @posts = Post.search(params[:keyword]).order(id: "DESC")
    redirect_to action: :index unless user_signed_in?
  end

  private
  def post_params
    params.require(:post).permit(:title, :date, :area_id, :postal, :place, :venue, :capacity, :remarks, :user_id).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  # def setting_post
  #   post = Post.find(params[:id])
  # end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_footer.html.haml
.footer

app/views/posts/_header.html.haml
.header
  .header__header-bar
    .header__header-bar__title
      = link_to posts_path, class: "btn-root" do
        Matching Baseball
    .header__header-bar__box
      .header__header-bar__box__post
        = link_to  new_post_path, class: "btn-post" do
          募集する
      .header__header-bar__box__user
        .dropdown
          %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
            = current_user.name
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li{:role => "presentation"}
              = link_to user_path(current_user) do
                = icon('fas', 'user')
                マイページ
            %li{:role => "presentation"}
              = link_to messages_path, class: "btn-edit" do
                = icon('fas', 'comments')
                メッセージ
            %li{:role => "presentation"}
              = link_to  destroy_user_session_path, method: :delete do
                = icon('fas', 'sign-out-alt')
                ログアウト

app/views/posts/_recruitment.html.haml
.recruitment
  - @posts.each do |post|
    .recruitment__content.wow.fadeInLeft
      .recruitment__content__title
        = post.title
      .recruitment__content__name
        募集者 : 
        = link_to user_path(post.user_id), class: "user--edit" do
          = post.user.name
      .recruitment__content__date
        開催日 : 
        = post.date
      .recruitment__content__place
        エリア : 
        = post.area_id
      .recruitment__content__application-btn
        = link_to post_path(post), class: "btn--edit" do
          詳細を見る
          
    

app/views/posts/_sub-header.html.haml
.header-bar-picture
  Let's play baseball together.

.header-bar-third
  .header-bar-third__information
    = icon('far', 'calendar-alt')
    募集情報

.header-bar-second
  .header-bar-second__search
    = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
      = icon('fas', 'search')
      = form.select :keyword, [ ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"], ["茨城県"], ["栃木県"] ,["群馬県"], ["埼玉県"], ["千葉県"], ["東京都"], ["神奈川県"] ,["新潟県"], ["富山県"], ["石川県"], ["福島県"], ["山梨県"] ,["長野県"], ["岐阜県"], ["静岡県"], ["愛知県"], ["三重県"] ,["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"], ["奈良県"] ,["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"] ,["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"] ,["佐賀県"], ["長崎県"], ["熊本県"], ["大分県"], ["宮崎県"] ,["鹿児島県"], ["沖縄県"] ], prompt: "エリア選択"
      = form.submit "検索", class: "search-btn" 

app/views/posts/create.html.haml
= render "header"
.post-done
  .post-done__success
    投稿が完了しました。
  .post-done__home
    = link_to posts_path, class: "btn-root" do
      投稿一覧へ戻る
  = render "footer"

app/views/posts/destroy.html.haml
= render "header"
.post-done
  .post-done__success
    削除が完了しました。
  .post-done__home
    = link_to posts_path, class: "btn-root" do
      投稿一覧へ戻る
  = render "footer"

app/views/posts/edit.html.haml
= render "header"
.header-title
  = icon('fas', 'pen')
  募集情報の編集

.content
  = form_with(model: @post, local: true) do |form|
    .content__title
      タイトル
      = form.text_field :title, placeholder: "タイトル 40文字以内" , rows: "40", class: 'title-box'
    .content__date
      開催日
      = form.date_field :date, placeholder: "", class: 'date-box'
    .content__area
      エリア
      .area-box
        = form.select :area_id, [ ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"], ["茨城県"], ["栃木県"] ,["群馬県"], ["埼玉県"], ["千葉県"], ["東京都"], ["神奈川県"] ,["新潟県"], ["富山県"], ["石川県"], ["福島県"], ["山梨県"] ,["長野県"], ["岐阜県"], ["静岡県"], ["愛知県"], ["三重県"] ,["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"], ["奈良県"] ,["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"] ,["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"] ,["佐賀県"], ["長崎県"], ["熊本県"], ["大分県"], ["宮崎県"] ,["鹿児島県"], ["沖縄県"] ], prompt: "選択してください"
    .content__place
      住所
      = form.text_field :postal, placeholder: "郵便番号", class: 'postal-box'
      = form.text_field :place, placeholder: "住所", class: 'place-box'
    .content__venue
      会場名
      = form.text_field :venue, placeholder: "会場名", class: 'venue-box'
    .content__capacity
      定員
      = form.number_field :capacity, placeholder: "選択", class: 'capacity-box'
    .content__remarks
      備考
      = form.text_area :remarks, placeholder: "備考を入力して下さい" , rows: "1000", class: 'remarks-box'
    .content__upload
      = form.submit :編集する, class: 'upload-box'
      .content__upload__destroy
        = link_to "/posts/#{@post.id}", method: :delete do
          = icon('fa', 'trash')

= render "footer"

app/views/posts/index.html.haml
.wrapper
  = render "header"
  = render "sub-header"
  = render "recruitment"
  = render "footer"

#page_top
  %a{href: "#"}

app/views/posts/new.html.haml
= render "header"

.header-title
  = icon('fas', 'pen')
  募集情報の新規作成

.content
  = form_with(model: @post, local: true) do |form|
    .content__title
      タイトル
      = form.text_field :title, placeholder: "タイトル 40文字以内" , rows: "40", class: 'title-box'
    .content__date
      開催日
      = form.date_field :date, placeholder: "", class: 'date-box'
    .content__area
      エリア
      .area-box
        = form.select :area_id, [ ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"], ["茨城県"], ["栃木県"] ,["群馬県"], ["埼玉県"], ["千葉県"], ["東京都"], ["神奈川県"] ,["新潟県"], ["富山県"], ["石川県"], ["福島県"], ["山梨県"] ,["長野県"], ["岐阜県"], ["静岡県"], ["愛知県"], ["三重県"] ,["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"], ["奈良県"] ,["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"] ,["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"] ,["佐賀県"], ["長崎県"], ["熊本県"], ["大分県"], ["宮崎県"] ,["鹿児島県"], ["沖縄県"] ], prompt: "選択してください"
    .content__place
      住所     
      = form.text_field :postal, placeholder: "郵便番号", class: 'postal-box'
      = form.text_field :place, placeholder: "住所", class: 'place-box'
    .content__venue
      会場名
      = form.text_field :venue, placeholder: "会場名", class: 'venue-box'
    .content__capacity
      定員
      = form.number_field :capacity, placeholder: "選択", class: 'capacity-box'
    .content__remarks
      備考
      = form.text_area :remarks, placeholder: "備考を入力して下さい" , rows: "1000", class: 'remarks-box'
    .content__upload
      = form.submit :投稿する, class: 'upload-box'
= render "footer"

app/views/posts/search.html.haml
= render "header"
.header-bar-third
  .header-bar-third__information
    検索結果

.search-top
  = form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
    = icon('fas', 'search')
    = form.select :keyword, [ ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"], ["茨城県"], ["栃木県"] ,["群馬県"], ["埼玉県"], ["千葉県"], ["東京都"], ["神奈川県"] ,["新潟県"], ["富山県"], ["石川県"], ["福島県"], ["山梨県"] ,["長野県"], ["岐阜県"], ["静岡県"], ["愛知県"], ["三重県"] ,["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"], ["奈良県"] ,["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"] ,["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"] ,["佐賀県"], ["長崎県"], ["熊本県"], ["大分県"], ["宮崎県"] ,["鹿児島県"], ["沖縄県"] ], prompt: "エリア選択"
    = form.submit "検索", class: "search-btn" 
.contents.row
  - @posts.each do |post|
    .recruitment__content.wow.fadeInLeft
      .recruitment__content__title
        = post.title
      .recruitment__content__name
        募集者 : 
        = link_to user_path(post.user_id), class: "user--edit" do
          = post.user.name
      .recruitment__content__date
        開催日 : 
        = post.date
      .recruitment__content__place
        エリア : 
        = post.area_id
      .recruitment__content__application-btn
        = link_to post_path(post), class: "btn--edit" do
          詳細を見る
= render "footer"

app/views/posts/show.html.haml
= render "header"
.show-content
  .show-content__show-title
    = @post.title
  .show-content__show-application
    .show-content__show-application__form-group
    - if @post.user.id == current_user.id
      = link_to  edit_post_path, class: "btn-edit" do
        = icon('fas', 'cog')
    - else
      - if @isRoom == true
        %p
          %a{href: "/rooms/#{@roomId}",class: "apply-btn"} 応募する
      - else
        = form_for @room do |f|
          = fields_for @entry do |e|
            = e.hidden_field :user_id, value: @post.user.id
          = f.submit "応募する",class: "apply-btn"
  .show-content__data
    .show-content__data__show-name
      　　募集者　　
      = link_to user_path(@post.user_id), class: "user--edit" do
        = @post.user.name
    .show-content__data__show-date
      　　開催日　　
      = @post.date
    .show-content__data__show-place
      .show-content__data__show-place__title
        住所
      .show-content__data__show-place__box
        .show-content__data__show-place__box__postal
          〒
          = @post.postal
        .show-content__data__show-place__box__write
          = @post.place
    .show-content__data__show-venue
      　　会場　　　
      = @post.venue
    .show-content__data__show-capacity
      　　定員　　　
      = @post.capacity
      人
    .show-content__data__show-remarks
      .show-content__data__show-remarks__title
        備考
      .show-content__data__show-remarks__write
        = @post.remarks
= render "footer"

app/views/posts/update.html.haml
= render "header"

.post-done
  .post-done__success
    更新が完了しました。
  .post-done__home
    = link_to posts_path, class: "btn-root" do
      投稿一覧へ戻る

  = render "footer"